FROM python:3
#  ENV PYTHONUNBUFFERED 1
# RUN mkdir /code
COPY . /root/app

WORKDIR /root/app




# ADD requirement.txt /code/
# RUN pip install -r requirement.txt
# ADD . /code/


# CMD [ "python" "test.py" ]